# Generated by Django 5.0.3 on 2024-06-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
